services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - ADDR=0.0.0.0:8080
      - CHAIN=gochain
    ports:
      - '8080:8080'
    restart: unless-stopped
