app = "gochain-demo"
primary_region = "iad"

[build]
dockerfile = "./api/Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines = "stop"
min_machines_running = 0
