// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: chain/v1/chain.proto

package chainv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{0}
}

func (x *GetBlockRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	PrevHash      []byte                 `protobuf:"bytes,3,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlockResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *GetBlockResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetBlockResponse) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

type SubmitTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          []byte                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxRequest) Reset() {
	*x = SubmitTxRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxRequest) ProtoMessage() {}

func (x *SubmitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxRequest.ProtoReflect.Descriptor instead.
func (*SubmitTxRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTxRequest) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SubmitTxRequest) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SubmitTxRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SubmitTxRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubmitTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        []byte                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxResponse) Reset() {
	*x = SubmitTxResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxResponse) ProtoMessage() {}

func (x *SubmitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxResponse.ProtoReflect.Descriptor instead.
func (*SubmitTxResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTxResponse) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       uint64                 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceResponse) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_chain_v1_chain_proto protoreflect.FileDescriptor

const file_chain_v1_chain_proto_rawDesc = "" +
	"\n" +
	"\x14chain/v1/chain.proto\x12\bchain.v1\x1a\x1cgoogle/api/annotations.proto\")\n" +
	"\x0fGetBlockRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"[\n" +
	"\x10GetBlockResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x1b\n" +
	"\tprev_hash\x18\x03 \x01(\fR\bprevHash\"a\n" +
	"\x0fSubmitTxRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\fR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"+\n" +
	"\x10SubmitTxResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\fR\x06txHash\"-\n" +
	"\x11GetBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x04R\abalance2\xb5\x02\n" +
	"\x05Chain\x12^\n" +
	"\bGetBlock\x12\x19.chain.v1.GetBlockRequest\x1a\x1a.chain.v1.GetBlockResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/blocks/{height}\x12[\n" +
	"\bSubmitTx\x12\x19.chain.v1.SubmitTxRequest\x1a\x1a.chain.v1.SubmitTxResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/tx:submit\x12o\n" +
	"\n" +
	"GetBalance\x12\x1b.chain.v1.GetBalanceRequest\x1a\x1c.chain.v1.GetBalanceResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/accounts/{address}/balanceB;Z9github.com/afrodynamic/gochain/api/proto/chain/v1;chainv1b\x06proto3"

var (
	file_chain_v1_chain_proto_rawDescOnce sync.Once
	file_chain_v1_chain_proto_rawDescData []byte
)

func file_chain_v1_chain_proto_rawDescGZIP() []byte {
	file_chain_v1_chain_proto_rawDescOnce.Do(func() {
		file_chain_v1_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_v1_chain_proto_rawDesc), len(file_chain_v1_chain_proto_rawDesc)))
	})
	return file_chain_v1_chain_proto_rawDescData
}

var file_chain_v1_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chain_v1_chain_proto_goTypes = []any{
	(*GetBlockRequest)(nil),    // 0: chain.v1.GetBlockRequest
	(*GetBlockResponse)(nil),   // 1: chain.v1.GetBlockResponse
	(*SubmitTxRequest)(nil),    // 2: chain.v1.SubmitTxRequest
	(*SubmitTxResponse)(nil),   // 3: chain.v1.SubmitTxResponse
	(*GetBalanceRequest)(nil),  // 4: chain.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 5: chain.v1.GetBalanceResponse
}
var file_chain_v1_chain_proto_depIdxs = []int32{
	0, // 0: chain.v1.Chain.GetBlock:input_type -> chain.v1.GetBlockRequest
	2, // 1: chain.v1.Chain.SubmitTx:input_type -> chain.v1.SubmitTxRequest
	4, // 2: chain.v1.Chain.GetBalance:input_type -> chain.v1.GetBalanceRequest
	1, // 3: chain.v1.Chain.GetBlock:output_type -> chain.v1.GetBlockResponse
	3, // 4: chain.v1.Chain.SubmitTx:output_type -> chain.v1.SubmitTxResponse
	5, // 5: chain.v1.Chain.GetBalance:output_type -> chain.v1.GetBalanceResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chain_v1_chain_proto_init() }
func file_chain_v1_chain_proto_init() {
	if File_chain_v1_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_v1_chain_proto_rawDesc), len(file_chain_v1_chain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chain_v1_chain_proto_goTypes,
		DependencyIndexes: file_chain_v1_chain_proto_depIdxs,
		MessageInfos:      file_chain_v1_chain_proto_msgTypes,
	}.Build()
	File_chain_v1_chain_proto = out.File
	file_chain_v1_chain_proto_goTypes = nil
	file_chain_v1_chain_proto_depIdxs = nil
}
