// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: wallet/v1/wallet.proto

package walletv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeeHint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxFeePerGas   uint64                 `protobuf:"varint,1,opt,name=max_fee_per_gas,json=maxFeePerGas,proto3" json:"max_fee_per_gas,omitempty"`
	MaxPriorityFee uint64                 `protobuf:"varint,2,opt,name=max_priority_fee,json=maxPriorityFee,proto3" json:"max_priority_fee,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FeeHint) Reset() {
	*x = FeeHint{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeHint) ProtoMessage() {}

func (x *FeeHint) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeHint.ProtoReflect.Descriptor instead.
func (*FeeHint) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *FeeHint) GetMaxFeePerGas() uint64 {
	if x != nil {
		return x.MaxFeePerGas
	}
	return 0
}

func (x *FeeHint) GetMaxPriorityFee() uint64 {
	if x != nil {
		return x.MaxPriorityFee
	}
	return 0
}

type Tx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           uint64                 `protobuf:"varint,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Nonce         uint64                 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tx) Reset() {
	*x = Tx{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *Tx) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Tx) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Tx) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Tx) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Tx) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Tx) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SignedTx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawHex        string                 `protobuf:"bytes,1,opt,name=raw_hex,json=rawHex,proto3" json:"raw_hex,omitempty"`
	TxId          string                 `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTx) Reset() {
	*x = SignedTx{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTx) ProtoMessage() {}

func (x *SignedTx) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTx.ProtoReflect.Descriptor instead.
func (*SignedTx) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *SignedTx) GetRawHex() string {
	if x != nil {
		return x.RawHex
	}
	return ""
}

func (x *SignedTx) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type NewKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          []byte                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewKeyRequest) Reset() {
	*x = NewKeyRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewKeyRequest) ProtoMessage() {}

func (x *NewKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewKeyRequest.ProtoReflect.Descriptor instead.
func (*NewKeyRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *NewKeyRequest) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type NewKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priv          string                 `protobuf:"bytes,1,opt,name=priv,proto3" json:"priv,omitempty"`
	Pub           string                 `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewKeyResponse) Reset() {
	*x = NewKeyResponse{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewKeyResponse) ProtoMessage() {}

func (x *NewKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewKeyResponse.ProtoReflect.Descriptor instead.
func (*NewKeyResponse) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *NewKeyResponse) GetPriv() string {
	if x != nil {
		return x.Priv
	}
	return ""
}

func (x *NewKeyResponse) GetPub() string {
	if x != nil {
		return x.Pub
	}
	return ""
}

func (x *NewKeyResponse) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ParseAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseAddressRequest) Reset() {
	*x = ParseAddressRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseAddressRequest) ProtoMessage() {}

func (x *ParseAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseAddressRequest.ProtoReflect.Descriptor instead.
func (*ParseAddressRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *ParseAddressRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ParseAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseAddressResponse) Reset() {
	*x = ParseAddressResponse{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseAddressResponse) ProtoMessage() {}

func (x *ParseAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseAddressResponse.ProtoReflect.Descriptor instead.
func (*ParseAddressResponse) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *ParseAddressResponse) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *BalanceRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       uint64                 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *BalanceResponse) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type BuildTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	FeeHint       *FeeHint               `protobuf:"bytes,4,opt,name=fee_hint,json=feeHint,proto3" json:"fee_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTxRequest) Reset() {
	*x = BuildTxRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTxRequest) ProtoMessage() {}

func (x *BuildTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTxRequest.ProtoReflect.Descriptor instead.
func (*BuildTxRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *BuildTxRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *BuildTxRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *BuildTxRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BuildTxRequest) GetFeeHint() *FeeHint {
	if x != nil {
		return x.FeeHint
	}
	return nil
}

type BuildTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *Tx                    `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTxResponse) Reset() {
	*x = BuildTxResponse{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTxResponse) ProtoMessage() {}

func (x *BuildTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTxResponse.ProtoReflect.Descriptor instead.
func (*BuildTxResponse) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *BuildTxResponse) GetTx() *Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

type SignTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priv          string                 `protobuf:"bytes,1,opt,name=priv,proto3" json:"priv,omitempty"`
	Tx            *Tx                    `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTxRequest) Reset() {
	*x = SignTxRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTxRequest) ProtoMessage() {}

func (x *SignTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTxRequest.ProtoReflect.Descriptor instead.
func (*SignTxRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *SignTxRequest) GetPriv() string {
	if x != nil {
		return x.Priv
	}
	return ""
}

func (x *SignTxRequest) GetTx() *Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

type SignTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signed        *SignedTx              `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTxResponse) Reset() {
	*x = SignTxResponse{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTxResponse) ProtoMessage() {}

func (x *SignTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTxResponse.ProtoReflect.Descriptor instead.
func (*SignTxResponse) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *SignTxResponse) GetSigned() *SignedTx {
	if x != nil {
		return x.Signed
	}
	return nil
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signed        *SignedTx              `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *BroadcastRequest) GetSigned() *SignedTx {
	if x != nil {
		return x.Signed
	}
	return nil
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *BroadcastResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type TxStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusRequest) Reset() {
	*x = TxStatusRequest{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusRequest) ProtoMessage() {}

func (x *TxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusRequest.ProtoReflect.Descriptor instead.
func (*TxStatusRequest) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *TxStatusRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type TxStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusResponse) Reset() {
	*x = TxStatusResponse{}
	mi := &file_wallet_v1_wallet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusResponse) ProtoMessage() {}

func (x *TxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_v1_wallet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusResponse.ProtoReflect.Descriptor instead.
func (*TxStatusResponse) Descriptor() ([]byte, []int) {
	return file_wallet_v1_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *TxStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_wallet_v1_wallet_proto protoreflect.FileDescriptor

const file_wallet_v1_wallet_proto_rawDesc = "" +
	"\n" +
	"\x16wallet/v1/wallet.proto\x12\twallet.v1\x1a\x1cgoogle/api/annotations.proto\"Z\n" +
	"\aFeeHint\x12%\n" +
	"\x0fmax_fee_per_gas\x18\x01 \x01(\x04R\fmaxFeePerGas\x12(\n" +
	"\x10max_priority_fee\x18\x02 \x01(\x04R\x0emaxPriorityFee\"|\n" +
	"\x02Tx\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\x04R\x03fee\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"8\n" +
	"\bSignedTx\x12\x17\n" +
	"\araw_hex\x18\x01 \x01(\tR\x06rawHex\x12\x13\n" +
	"\x05tx_id\x18\x02 \x01(\tR\x04txId\"#\n" +
	"\rNewKeyRequest\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\fR\x04seed\"J\n" +
	"\x0eNewKeyResponse\x12\x12\n" +
	"\x04priv\x18\x01 \x01(\tR\x04priv\x12\x10\n" +
	"\x03pub\x18\x02 \x01(\tR\x03pub\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\"+\n" +
	"\x13ParseAddressRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"*\n" +
	"\x14ParseAddressResponse\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"$\n" +
	"\x0eBalanceRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"+\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x04R\abalance\"{\n" +
	"\x0eBuildTxRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12-\n" +
	"\bfee_hint\x18\x04 \x01(\v2\x12.wallet.v1.FeeHintR\afeeHint\"0\n" +
	"\x0fBuildTxResponse\x12\x1d\n" +
	"\x02tx\x18\x01 \x01(\v2\r.wallet.v1.TxR\x02tx\"B\n" +
	"\rSignTxRequest\x12\x12\n" +
	"\x04priv\x18\x01 \x01(\tR\x04priv\x12\x1d\n" +
	"\x02tx\x18\x02 \x01(\v2\r.wallet.v1.TxR\x02tx\"=\n" +
	"\x0eSignTxResponse\x12+\n" +
	"\x06signed\x18\x01 \x01(\v2\x13.wallet.v1.SignedTxR\x06signed\"?\n" +
	"\x10BroadcastRequest\x12+\n" +
	"\x06signed\x18\x01 \x01(\v2\x13.wallet.v1.SignedTxR\x06signed\"(\n" +
	"\x11BroadcastResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"&\n" +
	"\x0fTxStatusRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"*\n" +
	"\x10TxStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xcb\x05\n" +
	"\x06Wallet\x12X\n" +
	"\x06NewKey\x12\x18.wallet.v1.NewKeyRequest\x1a\x19.wallet.v1.NewKeyResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/wallet:key\x12p\n" +
	"\fParseAddress\x12\x1e.wallet.v1.ParseAddressRequest\x1a\x1f.wallet.v1.ParseAddressResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/wallet/parseAddress\x12c\n" +
	"\aBalance\x12\x19.wallet.v1.BalanceRequest\x1a\x1a.wallet.v1.BalanceResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/wallet/{addr}/balance\x12_\n" +
	"\aBuildTx\x12\x19.wallet.v1.BuildTxRequest\x1a\x1a.wallet.v1.BuildTxResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/wallet:buildTx\x12[\n" +
	"\x06SignTx\x12\x18.wallet.v1.SignTxRequest\x1a\x19.wallet.v1.SignTxResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/wallet:signTx\x12g\n" +
	"\tBroadcast\x12\x1b.wallet.v1.BroadcastRequest\x1a\x1c.wallet.v1.BroadcastResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/wallet:broadcast\x12i\n" +
	"\bTxStatus\x12\x1a.wallet.v1.TxStatusRequest\x1a\x1b.wallet.v1.TxStatusResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/wallet/tx/{tx_id}/statusB=Z;github.com/afrodynamic/gochain/api/proto/wallet/v1;walletv1b\x06proto3"

var (
	file_wallet_v1_wallet_proto_rawDescOnce sync.Once
	file_wallet_v1_wallet_proto_rawDescData []byte
)

func file_wallet_v1_wallet_proto_rawDescGZIP() []byte {
	file_wallet_v1_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_v1_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_v1_wallet_proto_rawDesc), len(file_wallet_v1_wallet_proto_rawDesc)))
	})
	return file_wallet_v1_wallet_proto_rawDescData
}

var file_wallet_v1_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_wallet_v1_wallet_proto_goTypes = []any{
	(*FeeHint)(nil),              // 0: wallet.v1.FeeHint
	(*Tx)(nil),                   // 1: wallet.v1.Tx
	(*SignedTx)(nil),             // 2: wallet.v1.SignedTx
	(*NewKeyRequest)(nil),        // 3: wallet.v1.NewKeyRequest
	(*NewKeyResponse)(nil),       // 4: wallet.v1.NewKeyResponse
	(*ParseAddressRequest)(nil),  // 5: wallet.v1.ParseAddressRequest
	(*ParseAddressResponse)(nil), // 6: wallet.v1.ParseAddressResponse
	(*BalanceRequest)(nil),       // 7: wallet.v1.BalanceRequest
	(*BalanceResponse)(nil),      // 8: wallet.v1.BalanceResponse
	(*BuildTxRequest)(nil),       // 9: wallet.v1.BuildTxRequest
	(*BuildTxResponse)(nil),      // 10: wallet.v1.BuildTxResponse
	(*SignTxRequest)(nil),        // 11: wallet.v1.SignTxRequest
	(*SignTxResponse)(nil),       // 12: wallet.v1.SignTxResponse
	(*BroadcastRequest)(nil),     // 13: wallet.v1.BroadcastRequest
	(*BroadcastResponse)(nil),    // 14: wallet.v1.BroadcastResponse
	(*TxStatusRequest)(nil),      // 15: wallet.v1.TxStatusRequest
	(*TxStatusResponse)(nil),     // 16: wallet.v1.TxStatusResponse
}
var file_wallet_v1_wallet_proto_depIdxs = []int32{
	0,  // 0: wallet.v1.BuildTxRequest.fee_hint:type_name -> wallet.v1.FeeHint
	1,  // 1: wallet.v1.BuildTxResponse.tx:type_name -> wallet.v1.Tx
	1,  // 2: wallet.v1.SignTxRequest.tx:type_name -> wallet.v1.Tx
	2,  // 3: wallet.v1.SignTxResponse.signed:type_name -> wallet.v1.SignedTx
	2,  // 4: wallet.v1.BroadcastRequest.signed:type_name -> wallet.v1.SignedTx
	3,  // 5: wallet.v1.Wallet.NewKey:input_type -> wallet.v1.NewKeyRequest
	5,  // 6: wallet.v1.Wallet.ParseAddress:input_type -> wallet.v1.ParseAddressRequest
	7,  // 7: wallet.v1.Wallet.Balance:input_type -> wallet.v1.BalanceRequest
	9,  // 8: wallet.v1.Wallet.BuildTx:input_type -> wallet.v1.BuildTxRequest
	11, // 9: wallet.v1.Wallet.SignTx:input_type -> wallet.v1.SignTxRequest
	13, // 10: wallet.v1.Wallet.Broadcast:input_type -> wallet.v1.BroadcastRequest
	15, // 11: wallet.v1.Wallet.TxStatus:input_type -> wallet.v1.TxStatusRequest
	4,  // 12: wallet.v1.Wallet.NewKey:output_type -> wallet.v1.NewKeyResponse
	6,  // 13: wallet.v1.Wallet.ParseAddress:output_type -> wallet.v1.ParseAddressResponse
	8,  // 14: wallet.v1.Wallet.Balance:output_type -> wallet.v1.BalanceResponse
	10, // 15: wallet.v1.Wallet.BuildTx:output_type -> wallet.v1.BuildTxResponse
	12, // 16: wallet.v1.Wallet.SignTx:output_type -> wallet.v1.SignTxResponse
	14, // 17: wallet.v1.Wallet.Broadcast:output_type -> wallet.v1.BroadcastResponse
	16, // 18: wallet.v1.Wallet.TxStatus:output_type -> wallet.v1.TxStatusResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_wallet_v1_wallet_proto_init() }
func file_wallet_v1_wallet_proto_init() {
	if File_wallet_v1_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_v1_wallet_proto_rawDesc), len(file_wallet_v1_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_v1_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_v1_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_v1_wallet_proto_msgTypes,
	}.Build()
	File_wallet_v1_wallet_proto = out.File
	file_wallet_v1_wallet_proto_goTypes = nil
	file_wallet_v1_wallet_proto_depIdxs = nil
}
